version: '3'

services:

  db:
    container_name: theGreatAPI_store 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD: 
    ports:
      - 5432:5432
      
  api:
    container_name: theGreatAPI
    build: './api'
    depends_on: theGreatAPI_store
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      PG_CONNECTION_STRING:
    ports:
      - 3000:3000 # [local]:[exposed]
  