version: '3'

services:
  api:
    container_name: theGreatAPI
    build: './api'
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    ports:
      - 3000:3000 # [local]:[exposed]
  db:
    container_name: theGreatAPI_store 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD: 
    ports:
      - 5432:5432